# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:carbon
LABEL MAINTAINER "Subash SN"

WORKDIR /app

# Dependencies are installed at container startup from the mounted source tree.

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
