# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:16-bullseye
LABEL MAINTAINER "Subash SN"

WORKDIR /app

# Install build tools for native modules
RUN apt-get update && apt-get install -y python3 make g++ && rm -rf /var/lib/apt/lists/*

RUN npm install -g nodemon

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
