# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:20-bookworm-slim
LABEL MAINTAINER "Subash SN"

WORKDIR /app

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    make \
    g++ \
    libxml2-dev \
    libxslt1-dev \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g nodemon

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
