name: Security Tests

on:
  pull_request:
    branches:
      - '*'

permissions:
  checks: write
  contents: read

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 6.11.4 for app setup
        uses: actions/setup-node@v3
        with:
          node-version: '6.11.4'

      - name: Install dependencies
        run: |
          npm install

      - name: Set up Node.js 22 for testing
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install SecTester dependencies
        run: |
          npm i --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Start application using Docker Compose
        run: |
          docker-compose up --wait

      - name: Wait for application to be ready
        run: |
          chmod +x wait-for-it.sh
          ./wait-for-it.sh 127.0.0.1:9090 --timeout=60 --strict -- echo "Application is up"

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
          BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TARGET_URL: 'http://127.0.0.1:9090'
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
