name: Security Tests

on:
  pull_request:
    branches:
      - '*'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest
    env:
      MYSQL_USER: dvna
      MYSQL_DATABASE: dvna
      MYSQL_PASSWORD: passw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      BRIGHT_TARGET_URL: http://127.0.0.1:9090
      BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
      BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
      BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js 8.x for app setup
      uses: actions/setup-node@v3
      with:
        node-version: 8.x

    - name: Install application dependencies
      run: npm install

    - name: Create vars.env file
      run: |
        echo "MYSQL_USER=dvna" >> vars.env
        echo "MYSQL_DATABASE=dvna" >> vars.env
        echo "MYSQL_PASSWORD=passw0rd" >> vars.env
        echo "MYSQL_RANDOM_ROOT_PASSWORD=yes" >> vars.env

    - name: Start application
      run: docker compose up --wait

    - name: Check application readiness
      run: |
        for i in {1..10}; do
          nc -zv 127.0.0.1 9090 && echo "Application is ready" && exit 0
          echo "Waiting for application to be ready..."
          sleep 5
        done
        echo "Application did not become ready in time" && exit 1

    - name: Set up Node.js 22.x for tests
      uses: actions/setup-node@v3
      with:
        node-version: 22.x

    - name: Install SecTester dependencies
      run: npm i --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Run security tests
      run: |
        node --experimental-transform-types \
             --experimental-strip-types \
             --experimental-detect-module \
             --disable-warning=MODULE_TYPELESS_PACKAGE_JSON \
             --disable-warning=ExperimentalWarning \
             --test-force-exit \
             --test .brightsec/tests/*.test.ts \
             --test-concurrency=4