name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install SecTester dependencies
      run: npm install --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Set up Docker Compose
      run: |
        docker compose up --wait
      env:
        MYSQL_USER: ${{ secrets.MYSQL_USER }}
        MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_RANDOM_ROOT_PASSWORD: ${{ secrets.MYSQL_RANDOM_ROOT_PASSWORD }}

    - name: Wait for application to be ready
      run: |
        until nc -zv 127.0.0.1 9090; do
          echo "Waiting for application to be ready..."
          sleep 5
        done

    - name: Run security tests
      run: |
        node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
        --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
        --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
      env:
        BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
        BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
        BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRIGHT_TARGET_URL: 'http://127.0.0.1:9090'