name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 8.x
        uses: actions/setup-node@v3
        with:
          node-version: '8.x'

      - name: Install application dependencies
        run: npm install

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install SecTesterJS dependencies
        run: npm i --save=false @sectester/core @sectester/repeater @sectester/scan @sectester/runner

      - name: Create vars.env file
        run: echo -e "MYSQL_USER=dvna\nMYSQL_DATABASE=dvna\nMYSQL_PASSWORD=passw0rd\nMYSQL_RANDOM_ROOT_PASSWORD=yes" > vars.env

      - name: Start application
        run: docker compose up --wait

      - name: Wait for application to be ready
        run: |
          for i in {1..30}; do
            nc -zv 127.0.0.1 9090 && echo "Application is ready" && exit 0
            sleep 5
          done
          echo "Application did not become ready in time" && exit 1

      - name: Run security tests
        env:
          BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
          BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TARGET_URL: http://127.0.0.1:9090
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
