name: Security Tests

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: read

jobs:
  security-tests:
    runs-on: ubuntu-latest

    env:
      MYSQL_DATABASE: dvna
      MYSQL_PASSWORD: passw0rd
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: dvna
      BRIGHT_TARGET_URL: http://127.0.0.1:9090
      BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
      BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
      BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install SecTester dependencies
      run: npm install --save-dev @sectester/core @sectester/repeater @sectester/scan @sectester/runner

    - name: Start application using Docker Compose
      run: docker compose up --wait

    - name: Verify application readiness
      run: |
        for i in {1..10}; do
          if nc -zv 127.0.0.1 9090; then
            echo "Application is ready"
            break
          fi
          echo "Waiting for application to be ready..."
          sleep 5
        done

    - name: Run security tests
      run: |
        node --experimental-transform-types \
             --experimental-strip-types \
             --experimental-detect-module \
             --disable-warning=MODULE_TYPELESS_PACKAGE_JSON \
             --disable-warning=ExperimentalWarning \
             --test-force-exit \
             --test .brightsec/tests/*.test.ts \
             --test-concurrency=4